apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git@github.com:Efiop97/FoodistGitOps.git
    path: "apps/ingress-controller"
    targetRevision: HEAD
    helm:
      values: |
        installCRDs: true
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
